### ISSUE TITLE
A Windows (32/64) release compatible with  AeonWave 3.9.1?

### ISSUE THREAD

**Issue by donizettilorenzo** [adalinbv/libaaxopenal#1]
As the title says.....

I'd like to compare to OpenAL Soft.

**Comment by ermarch** [comment]
To be honest, the AeonWave OpenAL layer is in maintenance mode only.
The focus has shifted towards native AeonWave support which is far superior.

**Comment by donizettilorenzo** [comment]
But it's working with new AeonWave release? Can you provide some binaries for AeonWave 3.9.x ?

**Comment by ermarch** [comment]
It should be working, and I just realized the executable is still on the server:
http://adalin.com/downloads/AeonWave-OpenAL-1.1.33.exe

Note that I did not test it.

**Comment by ermarch** [comment]
Okay, that one didn't work since it was compiled against a 32-bit version of AeonWave.
There is now a new version: http://adalin.com/downloads/AeonWave-OpenAL-1.1.40.exe

**Comment by donizettilorenzo** [comment]
Thanks! Will test!

Il giorno gio 25 feb 2021 alle ore 08:46 ermarch <notifications@github.com>
ha scritto:

**Comment by ThreeDeeJay** [comment]
Any luck getting it to work? I'd also like to compare the HRTF to OpenAL Soft and overall performance/features.
However, I can't even get AeonWave working in general. It either crashes ([aaxplaymidi.exe](https://i.imgur.com/RJC5ZuU.png), [aaxplayer.exe](https://i.imgur.com/CkipsIs.png) and [aaxrecorder.exe](https://i.imgur.com/KvbUub8.png)), audio crackling ([aaxplay.exe](https://i.imgur.com/hLN5DOb.png)), and when using AeonWave-OpenAL, it detects the device name but refuses to initialize (OpenAL SDK [EFX10ShowWin64](https://i.imgur.com/9EOMmGr.png), [PlayMultiChannelWin64.exe](https://i.imgur.com/8wQiJl6.png), etc) or straight up freezes ([Dolphin emulator](https://i.imgur.com/d8LG8Ag.png)).

I have so many questions, like:
- Are there new AeonWave-OpenAL binaries for Windows?
- Does this require purchasing AeonWave?
- Are there any audio/video demos? 
- Are there any existing apps/games that (can) use AeonWave?
- Does proper installation require anything other than installing AeonWave-3.10.0.exe, AeonWave-utils-2.3.0.exe, AeonWave-Support-1.3.5.exe, AeonWave-OpenAL-1.1.40.exe and configuring config.xml using aaxconfig.exe?
On a side note, it seems aaxconfig.exe overwrites config.xml with the defaults, and AeonWave-OpenAL copies 64-bit DLLs into SysWOW64 (meant for 32-bit DLLs) which might explain why it [doesn't get detected by 32-bit apps](https://i.imgur.com/b4R3sCl.png) even tho [it does for 64-bit apps](https://i.imgur.com/6GeM9pT.png).

**Comment by ermarch** [comment]
AeonWave OpenAL is not officially supported anymore. If it works it works otherwise you'll be out of luck.

**Comment by ThreeDeeJay** [comment]
That's unfortunate, guess I _am_ fresh out of luck 🥲
Are there any demos of native AeonWave tho? The [tech's specs](https://adalin.com/downloads/TechSpecs.pdf) are pretty impressive but I haven't found any audio/video clips of its in action so I'm really curious, particularly the headphone HRTF and multi-speaker spatial modes.

**Comment by ermarch** [comment]
You could argue this is a good example of it's capabilities, but it's not very interesting from a 3D/4D point of view:
http://adalin.com/index.html?frame=midi/nonfree.html

It's just a static scene with all emitters positioned around the sensor rendered to stereo, possibly with (3D) reverb enabled.
At this moment there are no other demos  available.

**Comment by ThreeDeeJay** [comment]
Thanks, that's pretty cool! I've always wanted a MIDI player with 3D HRTF animation capabilities, kinda like [this](https://youtu.be/EmuWIuI9e-c). 
On a side note, the other day I found out the MPT chiptune format supports quad surround natively so I re-mixed a couple tracks in (virtual) surround [here](https://airtable.com/shrkgzXy1RYUpEh1z/tblZ8QmkQmfZuoquV).
Anyhow, do you happen to still have a copy of http://adalin.com/downloads/AeonWave-OpenAL-1.1.33.exe (link's down) or perhaps http://adalin.com/downloads/AeonWave-OpenAL-1.1.40.exe, but for 32 bits?
I'd like to run more tests but 64-bit OpenAL games are almost non-existent, and compiling myself yields a barrage of errors I have no idea how to fix 😅

**Comment by ermarch** [comment]
The biggest problem with that is that AeonWave itself switched to 64-bit only, which makes perfectly sense for AeonWave.
But not for OpenAL apparently. And you can't mix 32-bit and 64-bit libraries on Windows.

**Comment by ThreeDeeJay** [comment]
I see, that's understandable 👌
